<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(                                                                                     
    'Middleware\Module'
        => __DIR__ . '/Module.php',
    'Middleware\Service\Factory\MiddlewareServiceFactory'
        => __DIR__ . '/src/Middleware/Service/Factory/MiddlewareServiceFactory.php',
    'Middleware\Service\MiddlewareService'
        => __DIR__ . '/src/Middleware/Service/MiddlewareService.php',
    'Middleware\Listener\MiddlewareListener'
        => __DIR__ . '/src/Middleware/Listener/MiddlewareListener.php',
    'Middleware\Entity\Middleware'
        => __DIR__ . '/src/Middleware/Entity/Middleware.php'
);
